import 'dart:io';

/// Generates integration_test/test_fixtures.dart from .bin and _headers.txt files
/// in test/fixtures/responses/
void main() {
  final fixturesDir = Directory('test/fixtures/responses');
  final outputFile = File('integration_test/test_fixtures.dart');

  // Ensure integration_test directory exists
  outputFile.parent.createSync(recursive: true);

  final fixtures = [
    'oref_alerts',
    'oref_history',
    'oref_districts',
    'oref_cities',
    'rss_ynet',
    'rss_maariv',
    'rss_haaretz',
  ];

  final buffer = StringBuffer();
  buffer.writeln("// GENERATED FILE - DO NOT EDIT MANUALLY");
  buffer.writeln("// Generated by tool/generate_test_fixtures.dart");
  buffer.writeln("");
  buffer.writeln("import 'package:http/http.dart' as http;");
  buffer.writeln("");
  buffer.writeln("class TestFixtures {");

  final byteConstants = <String, String>{};

  for (final fixture in fixtures) {
    final binFile = File('${fixturesDir.path}/${fixture}_body.bin');
    final headersFile = File('${fixturesDir.path}/${fixture}_headers.txt');

    if (!binFile.existsSync()) {
      continue;
    }

    final constName = '_${_toLowerCamelCase(fixture)}Bytes';
    byteConstants[fixture] = constName;

    // Extract content-type from headers
    String contentType = 'application/octet-stream';
    if (headersFile.existsSync()) {
      contentType = _extractContentType(headersFile.readAsStringSync());
    }

    // Generate getter
    final getterName = _toLowerCamelCase(fixture);
    buffer.writeln(
      "  static http.Response get $getterName => http.Response.bytes(",
    );
    buffer.writeln("    $constName, 200,");
    buffer.writeln("    headers: {'content-type': '$contentType'},");
    buffer.writeln("  );");
    buffer.writeln("");
  }

  buffer.writeln("  // Byte constants");
  for (final entry in byteConstants.entries) {
    final bytes = File(
      '${fixturesDir.path}/${entry.key}_body.bin',
    ).readAsBytesSync();
    buffer.writeln(
      "  static const ${entry.value} = ${_bytesToDartList(bytes)};",
    );
  }

  buffer.writeln("}");

  outputFile.writeAsStringSync(buffer.toString());
}

String _toLowerCamelCase(String value) {
  final parts = value.split('_');
  if (parts.isEmpty) return value;

  return parts.first +
      parts.skip(1).map((part) {
        if (part.isEmpty) return part;
        return part[0].toUpperCase() + part.substring(1);
      }).join();
}

String _bytesToDartList(List<int> bytes) {
  if (bytes.isEmpty) return '<int>[]';

  final buffer = StringBuffer('<int>[');
  for (var i = 0; i < bytes.length; i++) {
    if (i > 0) buffer.write(', ');
    // Add newline every 16 bytes for readability
    if (i > 0 && i % 16 == 0) buffer.write('\n    ');
    buffer.write('0x${bytes[i].toRadixString(16).padLeft(2, '0')}');
  }
  buffer.write(']');
  return buffer.toString();
}

String _extractContentType(String headers) {
  final lines = headers.split('\n');
  for (final line in lines) {
    final lower = line.toLowerCase();
    if (lower.startsWith('content-type:')) {
      var value = line.substring(line.indexOf(':') + 1).trim();
      // Remove charset for simplicity, http.Response handles it
      if (value.contains(';')) {
        value = value.substring(0, value.indexOf(';')).trim();
      }
      return value;
    }
  }
  return 'application/octet-stream';
}
