name: Manual Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy (commit SHA or "latest")'
        required: true
        default: 'latest'
        type: string
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Verify image exists
      run: |
        echo "Checking if image exists: me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mklat-news/mklat-news:${{ inputs.image_tag }}"
        gcloud container images describe me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mklat-news/mklat-news:${{ inputs.image_tag }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy mklat-news-service \
          --image me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mklat-news/mklat-news:${{ inputs.image_tag }} \
          --platform managed \
          --region me-west1 \
          --allow-unauthenticated \
          --set-env-vars NODE_ENV=production \
          --memory 1Gi \
          --cpu 1 \
          --min-instances 1 \
          --max-instances 10 \
          --concurrency 100 \
          --timeout 300 \
          --port 3000

    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe mklat-news-service --region=me-west1 --format='value(status.url)')
        echo "Service deployed successfully!"
        echo "Service URL: $SERVICE_URL"
        echo "Image deployed: me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mklat-news/mklat-news:${{ inputs.image_tag }}"
